# Generated by Django 3.0.5 on 2021-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Titulo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.TextField(default='hola chao chao')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
