# Generated by Django 3.0.5 on 2021-05-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Titulo', max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.TextField(default='default message')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('user', models.CharField(default='usuario', max_length=150)),
                ('url', models.URLField(default='url/gsj')),
                ('location', models.CharField(default='paisciudad', max_length=150)),
                ('language', models.CharField(default='idioma', max_length=150)),
                ('num_retweets', models.IntegerField(default=0)),
            ],
        ),
    ]
