version: '3.1'

volumes:
  init-db:
  data-db:

services:
  mongodb:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario
      MONGO_INITDB_ROOT_PASSWORD: secreto
      MONGO_INITDB_DATABASE: tweetapi
    ports:
      - 27017:27017


  web:
    image: miqpanbas/cbd-tweetmaps
    restart: always
    command: bash -c "python manage.py setup && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - mongodb

