version: '3.1'

volumes:
  init-db:
  data-db:

services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario
      MONGO_INITDB_ROOT_PASSWORD: secreto
      MONGO_INITDB_DATABASE: tweetapi
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin

  web:
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/TweetMaps
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - migration

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/TweetMaps
    links:
      - mongodb
    depends_on:
      - make_migrations

  make_migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
      - .:/TweetMaps
    links:
      - mongodb
    depends_on:
      - mongodb
